module.exports={
    devServer:{
        port:8888,
        open:true,
        host:'localhost'
    },
    configureWebpack:{
        resolve:{
            alias:{
                'assets':'@/assets'
            }
        }
    }
}
